import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import path from 'node:path';
import test from 'node:test';

import {
  SIDEBAR_ALLOWLIST,
  checkSidebarReachability,
  collectSidebarDocIds,
  docIdFromPage,
  listPublishedJaPages,
} from '../scripts/check-sidebar-reachability.mjs';

const REPO_ROOT = path.resolve(import.meta.dirname, '..');

/** 実 sidebars.js から doc ID 集合を読む（改変して注入するため）。 */
function realSidebarIds() {
  const require = createRequire(import.meta.url);
  return collectSidebarDocIds(require(path.join(REPO_ROOT, 'sidebars.js')));
}

test('docIdFromPage derives the ID from the path and honours a frontmatter id', () => {
  assert.equal(docIdFromPage('guides/faq.md', undefined), 'guides/faq');
  assert.equal(docIdFromPage('index.md', undefined), 'index');
  assert.equal(docIdFromPage('use-cases/index.md', 'use-cases-index'), 'use-cases/use-cases-index');
  assert.equal(docIdFromPage('dashboard.md', 'dashboard'), 'dashboard');
  assert.equal(docIdFromPage('guides/faq.md', '   '), 'guides/faq');
});

test('collectSidebarDocIds walks strings, doc/ref items, and category links', () => {
  const ids = collectSidebarDocIds({
    docs: [
      'index',
      { type: 'doc', id: 'guides/a' },
      { type: 'ref', id: 'guides/b' },
      {
        type: 'category',
        label: 'C',
        link: { type: 'doc', id: 'guides/c-index' },
        items: ['guides/c1', { type: 'category', label: 'N', items: ['guides/c2'] }],
      },
      { type: 'link', label: 'ext', href: 'https://example.com' },
    ],
  });
  assert.deepEqual(
    [...ids].sort(),
    ['guides/a', 'guides/b', 'guides/c-index', 'guides/c1', 'guides/c2', 'index'].sort()
  );
});

test('collectSidebarDocIds throws on an unknown item shape instead of skipping it', () => {
  // 未知の形状を黙って読み飛ばすと、その配下の doc が「未掲載」と誤判定される
  // （= 検証の空振り）ため、throw する仕様を固定する。
  assert.throws(
    () => collectSidebarDocIds({ docs: [{ type: 'autogenerated', dirName: 'guides' }] }),
    /未知の item/
  );
});

test('listPublishedJaPages applies the enumeration contract to fixture pages', async () => {
  const { pages, errors } = await listPublishedJaPages('tests/fixtures/sidebar-reachability');
  assert.deepEqual(errors, []);
  // .en.md / draft / unlisted / `_` 始まりは除外され、frontmatter id は反映される。
  assert.deepEqual(
    pages.map((p) => p.docId),
    ['plain', 'renamed', 'sub/nested']
  );
});

test('listPublishedJaPages resolves the real use-cases index through its frontmatter id', async () => {
  // issue #1727 の実測（51 本）と本 checker の実測がずれる代表例。
  // use-cases/index.md は frontmatter `id: use-cases-index` で sidebar に載っている。
  const { pages } = await listPublishedJaPages();
  const ids = new Set(pages.map((p) => p.docId));
  assert.ok(ids.has('use-cases/use-cases-index'));
  assert.ok(!ids.has('use-cases/index'));
  assert.ok(ids.has('guides/faq'));
});

test('checkSidebarReachability passes on the current repo state', async () => {
  const { errors, reachable, allowlisted } = await checkSidebarReachability();
  assert.deepEqual(errors, [], `Expected no errors but got: ${errors.join(', ')}`);
  const { pages } = await listPublishedJaPages();
  // 全ページが「sidebar 掲載」か「理由付き allowlist」のどちらかに落ちる。
  assert.equal(reachable + allowlisted, pages.length);
  assert.equal(allowlisted, Object.keys(SIDEBAR_ALLOWLIST).length);
});

// --- 実測データの改変版に当てる（自己整合なテストにしないため） ---
//
// 失敗系を偽データだけで書くと、production の列挙・抽出が実リポジトリで別の
// 集合を掴んでいても通ってしまう。ここでは実ページ・実 sidebar の測定結果を
// 1 箇所だけ壊し、「本当に落ちる」ことを確かめる。

test('a real page dropped from the sidebar is reported as unreachable', async () => {
  const sidebarIds = realSidebarIds();
  assert.ok(sidebarIds.delete('guides/quickstart'), 'fixture precondition: quickstart is listed');
  const { errors } = await checkSidebarReachability({ sidebarIds });
  assert.equal(errors.length, 1);
  assert.match(errors[0], /pages\/guides\/quickstart\.md \(doc ID "guides\/quickstart"\) が/);
  assert.match(errors[0], /sidebars\.js に載っていない/);
});

test('removing a real allowlist entry makes the check fail', async () => {
  const allowlist = { ...SIDEBAR_ALLOWLIST };
  assert.ok(
    'reference/skill-metadata' in allowlist,
    'fixture precondition: reference/skill-metadata is allowlisted'
  );
  delete allowlist['reference/skill-metadata'];
  const { errors } = await checkSidebarReachability({ allowlist });
  assert.equal(errors.length, 1);
  assert.match(
    errors[0],
    /pages\/reference\/skill-metadata\.md \(doc ID "reference\/skill-metadata"\) が/
  );
});

test('an allowlist entry for a page already in the sidebar is reported as expired', async () => {
  const allowlist = { ...SIDEBAR_ALLOWLIST, 'guides/quickstart': '掲載済みのはず' };
  const { errors } = await checkSidebarReachability({ allowlist });
  assert.equal(errors.length, 1);
  assert.match(errors[0], /SIDEBAR_ALLOWLIST\["guides\/quickstart"\] は sidebar に掲載済み/);
});

test('an allowlist entry for a nonexistent page is reported as expired', async () => {
  const allowlist = { ...SIDEBAR_ALLOWLIST, 'guides/removed-page': 'かつて存在した' };
  const { errors } = await checkSidebarReachability({ allowlist });
  assert.equal(errors.length, 1);
  assert.match(
    errors[0],
    /SIDEBAR_ALLOWLIST\["guides\/removed-page"\] は公開対象の日本語ページに存在しない/
  );
});

test('a reason-less allowlist entry is rejected and the page still reported', async () => {
  const allowlist = { ...SIDEBAR_ALLOWLIST, 'reference/skill-metadata': '' };
  const { errors } = await checkSidebarReachability({ allowlist });
  assert.equal(errors.length, 2);
  assert.ok(errors.some((e) => e.includes('ignoreKeys["reference/skill-metadata"] に理由が無い')));
  // resolveIgnoreKeys 再利用のメッセージに、修正対象が SIDEBAR_ALLOWLIST だと分かる注記が付く。
  assert.ok(
    errors.some((e) =>
      e.includes('（修正対象: scripts/check-sidebar-reachability.mjs の SIDEBAR_ALLOWLIST）')
    )
  );
  // 理由なしの除外は採用されないため、そのページは通常どおり未掲載として報告される。
  assert.ok(errors.some((e) => e.includes('pages/reference/skill-metadata.md')));
});

test('a sidebar entry without a matching Japanese page is reported', async () => {
  const sidebarIds = realSidebarIds();
  sidebarIds.add('guides/phantom-page');
  const { errors } = await checkSidebarReachability({ sidebarIds });
  assert.equal(errors.length, 1);
  assert.match(errors[0], /sidebars\.js が "guides\/phantom-page" を挙げているが/);
});

test('duplicate doc IDs across pages are reported', async () => {
  const { pages } = await listPublishedJaPages();
  const duplicated = [...pages, { relPath: 'guides/faq-copy.md', docId: 'guides/faq' }];
  const { errors } = await checkSidebarReachability({ pages: duplicated });
  assert.equal(errors.length, 1);
  assert.match(errors[0], /doc ID "guides\/faq" が重複している/);
});

test('empty measurements are errors, not a vacuous pass', async () => {
  const emptyPages = await checkSidebarReachability({ pages: [], pageErrors: [] });
  assert.ok(emptyPages.errors.some((e) => e.includes('日本語ページが 1 件も無い')));

  const { pages } = await listPublishedJaPages();
  const emptySidebar = await checkSidebarReachability({ pages, sidebarIds: new Set() });
  assert.ok(emptySidebar.errors.some((e) => e.includes('doc ID を 1 件も抽出できない')));
});

test('every allowlist entry carries a non-empty reason', () => {
  for (const [docId, reason] of Object.entries(SIDEBAR_ALLOWLIST)) {
    assert.ok(
      typeof reason === 'string' && reason.trim() !== '',
      `SIDEBAR_ALLOWLIST["${docId}"] must carry a reason`
    );
  }
});
