name: "\u26A1 Enhancement"
description: 'Polish or extend an existing River Reviewer capability.'
title: '[Enhancement] '
labels: ['type:enhancement', 'status:triage']
body:
  - type: markdown
    attributes:
      value: 'Tell us how to make the current flow smoother.'
  - type: dropdown
    id: phase
    attributes:
      label: 'What phase is affected?'
      options:
        - upstream
        - midstream
        - downstream
    validations:
      required: true
  - type: dropdown
    id: schema_impacted
    attributes:
      label: 'Schema impacted? (skill.schema.json)'
      options:
        - Yes
        - No
        - Unsure
    validations:
      required: true
  - type: dropdown
    id: runner_logic_impacted
    attributes:
      label: 'Runner logic impacted?'
      options:
        - Yes
        - No
        - Unsure
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: 'Impact level'
      options:
        - info
        - minor
        - major
        - critical
    validations:
      required: true
  - type: textarea
    id: current
    attributes:
      label: 'Current behavior'
      description: 'Summarize what exists today and any friction.'
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: 'Requested enhancement'
      description: 'How should the flow improve across Upstream → Midstream → Downstream?'
    validations:
      required: true
  - type: checkboxes
    id: docs_impact
    attributes:
      label: 'Documentation impact / ドキュメントへの影響'
      description: 'Does this enhancement require documentation updates?'
      options:
        - label: 'No（不要）'
        - label: 'Yes（必要）'
    validations:
      required: true
  - type: checkboxes
    id: diataxis_type
    attributes:
      label: 'If yes, which Diátaxis type(s) do you expect?（複数選択可）'
      options:
        - label: 'Tutorial（チュートリアル / 新しいユーザー向け）'
        - label: 'How-to guide（ハウツー / 特定タスク向け）'
        - label: 'Reference（リファレンス / API・設定・スキーマ）'
        - label: 'Explanation（解説 / 背景や設計）'
  - type: textarea
    id: success
    attributes:
      label: 'Success signals'
      description: 'Metrics, usability wins, or quality checks that confirm the enhancement worked.'
    validations:
      required: true
