name: '✨ Feature request'
description: 機能追加・改善提案
title: '[Feature]: '
labels: ['type:feature', 'status:triage']
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: 何が困っている／何が足りない？
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: こうしたい、という提案
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Scope / Out of scope
      placeholder: |
        In scope:
        - ...
        Out of scope:
        - ...
  - type: textarea
    id: done
    attributes:
      label: Definition of Done
      description: どこまでできたら完了か
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P0
        - P1
        - P2
    validations:
      required: true
