name: "\U0001F4DA 用語提案/\u8868記整合"
labels: ["doc:terminology"]
body:
  - type: input
    id: term
    attributes:
      label: 用語/表記（日本語・英語）
  - type: textarea
    id: rationale
    attributes:
      label: 採用したい理由・出典
